
#ifndef __ERROR_CODE_H__
#define __ERROR_CODE_H__

#pragma once

#define ERROR_CODE_ACCOUNT_AUTH_OK 1
#define ERROR_CODE_ACCOUNT_NOT_MATCH 0
#define ERROR_CODE_ACCOUNT_NOT_EXIST -1
#define ERROR_CODE_ACCOUNT_ALREADY_LOGIN -2
#define ERROR_CODE_ACCOUNT_OTHER_LOGIN -3
#define ERROR_CODE_PACKET_ERROR -4
#define ERROR_CODE_PACKET_UNKONWN -5
#define ERROR_CODE_SERVER_BUSY -6
#define ERROR_CODE_SERVER_SHUTDOWN -7
#define ERROR_CODE_CLIENT_TIMEOUT -8

#define ERROR_CODE_BAD_APP -11
#define ERROR_CODE_INVALID_ENCKEYLENGTH -12
#define ERROR_CODE_INVALID_ENCNONCELENGTH -13
#define ERROR_CODE_HACKED_CLIENT -14

#endif //__ERROR_CODE_H__